# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e0c1472b47e6a75dca3b7d22a4672430bb3cf217894e6ca203494b003897c38f669b180a21ac5adfd7fe968c58ccf5f51bf0c0dffc64faf78502a6ac264d7e1

test:
  secret_key_base: 9349dcf5eb60e34726fc4b168b5f8a84c7a28bb3e1518694b48913bc40749a2b7d9823f3c2a23963b6e9e690b85f34b4f5ebc631a86158644adf7d5577d5fa97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
